name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [0, 1,2] # Adjust based on the number of groups

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Split test files
        run: node split-tests.js 3 test-groups.json

      - name: Run Cypress tests
        run: |
          GROUP=$(cat test-groups.json | jq -r ".[$MATRIX_GROUP]")
          echo $GROUP | jq -c '.[]' | xargs -n 1 npx cypress run --spec
        env:
          MATRIX_GROUP: ${{ matrix.group }}
